(()=>{'use strict';
const C=SZCore,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false}),radar=$('radar'),rctx=radar.getContext('2d');let W=0,H=0,DPR=1;
function resize(){DPR=Math.min(devicePixelRatio||1,1.35);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const MW=36,MH=36,map=Array.from({length:MH},(_,y)=>Array.from({length:MW},(_,x)=>(x<1||y<1||x>=MW-1||y>=MH-1)?1:0));
function wall(x,y,w,h,t=1){for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)if(map[j])map[j][i]=t}wall(6,4,1,12);wall(6,19,1,12);wall(13,1,1,9);wall(13,14,1,15);wall(20,5,1,11);wall(20,20,1,14);wall(27,1,1,8);wall(27,13,1,18);wall(1,11,8,1);wall(11,11,7,1);wall(22,11,12,1);wall(4,18,11,1);wall(18,18,12,1);wall(9,26,11,1);wall(23,26,11,1);wall(15,7,3,2,2);wall(23,15,3,2,3);wall(10,22,2,2,3);wall(30,21,2,2,2);
const weapons=[
{name:'VX-7 CARBINE',mode:'AUTO · 5.56 AP',mag:30,max:30,res:180,dmg:24,rate:92,reload:1750,spread:.018,recoil:.025,pellets:1,range:34,fall:17,min:.62,auto:true,color:'#ffd67a'},
{name:'K-11 BREACHER',mode:'PUMP · 12 GA',mag:8,max:8,res:48,dmg:17,rate:680,reload:2250,spread:.14,recoil:.095,pellets:8,range:18,fall:6,min:.35,auto:false,color:'#ffb05d'},
{name:'VANTA SMG',mode:'AUTO · 9×19',mag:36,max:36,res:216,dmg:15,rate:64,reload:1450,spread:.045,recoil:.018,pellets:1,range:25,fall:10,min:.55,auto:true,color:'#d7eeff'},
{name:'M99 LONGBOW',mode:'BOLT · .338',mag:5,max:5,res:30,dmg:110,rate:1050,reload:2600,spread:.002,recoil:.14,pellets:1,range:42,fall:30,min:.8,auto:false,color:'#bdeaff'}];
let p,enemies=[],shots=[],particles=[],shells=[],pickups=[],barrels=[],weather=[],state='menu',last=0,fireHeld=false,ads=false,sprinting=false,reloading=false,reloadAt=0,weapon=0,nextWaveAt=0,shake=0,flash=0,damageFlash=0,audio=null,spawnClock=0;
function reset(){p={x:3.5,y:3.5,a:0,hp:100,armor:75,stamina:100,score:0,wave:1,kills:0,waveKills:0,combo:1,comboAt:0,bob:0,kick:0,alive:true};enemies=[];shots=[];particles=[];pickups=[];barrels=[{x:11.5,y:15.5,hp:45},{x:18.5,y:23.5,hp:45},{x:29.5,y:8.5,hp:45}];weapons.forEach(w=>{w.mag=w.max;w.res=w.max*6});weapon=0;reloading=false;nextWaveAt=0;spawnClock=0;for(let i=0;i<5;i++)spawnEnemy();hud();notice('行动开始','守住中继站并消灭来袭部队')}
function initAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)()}
function tone(f,d,type='square',v=.035,slide=0){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);if(slide)o.frequency.linearRampToValueAtTime(f+slide,audio.currentTime+d);g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function sfx(kind){initAudio();if(kind==='shot'){tone(weapon===1?75:weapon===3?240:145,.07,'sawtooth',weapon===1?.13:.065,-80);tone(45,.09,'triangle',.09)}else if(kind==='hit')tone(680,.035,'square',.025);else if(kind==='kill'){tone(520,.05,'square',.04);setTimeout(()=>tone(800,.06,'sine',.035),45)}else if(kind==='hurt')tone(90,.12,'sawtooth',.06,-50);else if(kind==='reload'){tone(430,.03,'square',.025);setTimeout(()=>tone(650,.035,'square',.025),180)}else if(kind==='boom'){tone(65,.25,'sawtooth',.14,-45)}}
function solid(x,y){const ix=Math.floor(x),iy=Math.floor(y);return ix<0||iy<0||ix>=MW||iy>=MH||map[iy][ix]>0}
function ray(x,y,a,max=42){const dx=Math.cos(a),dy=Math.sin(a);for(let d=.02;d<max;d+=.045){const xx=x+dx*d,yy=y+dy*d;if(solid(xx,yy))return{d,x:xx,y:yy,t:map[Math.floor(yy)][Math.floor(xx)]}}return{d:max,x:x+dx*max,y:y+dy*max,t:0}}
function clearLine(x1,y1,x2,y2){const d=Math.hypot(x2-x1,y2-y1),a=Math.atan2(y2-y1,x2-x1);return ray(x1,y1,a,d).d>=d-.15}
function spawnEnemy(forceBoss=false){let x,y,n=0;do{x=2+Math.random()*(MW-4);y=2+Math.random()*(MH-4);n++}while((solid(x,y)||Math.hypot(x-p.x,y-p.y)<8)&&n<80);if(n>=80)return;let type=forceBoss?'juggernaut':Math.random()<.16?'rusher':Math.random()<.18?'marksman':'rifle';const cfg={rifle:[58,1.25,8,.75,'#8e493d'],rusher:[42,2.2,10,.55,'#c47a3b'],marksman:[48,.85,16,.65,'#596d78'],juggernaut:[420,.68,21,1.28,'#8b2925']}[type];enemies.push({x,y,type,hp:cfg[0]*(1+(p.wave-1)*.08),max:cfg[0]*(1+(p.wave-1)*.08),speed:cfg[1],damage:cfg[2],size:cfg[3],color:cfg[4],cool:500+Math.random()*500,hit:0,dead:false,elite:type==='juggernaut'});if(forceBoss){$('boss').style.display='block';$('bossName').textContent='重装执行者 · JUGGERNAUT'}}
function particle(x,y,color,count=8,power=3,life=500){for(let i=0;i<count;i++){const a=Math.random()*6.28,s=Math.random()*power;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life,max:life,size:1+Math.random()*3,color});}if(particles.length>260)particles.splice(0,particles.length-260)}
function shoot(){if(state!=='play'||reloading)return;const w=weapons[weapon],now=performance.now();if(now-(shoot.last||0)<w.rate)return;if(w.mag<=0){reload();return}shoot.last=now;w.mag--;p.kick=Math.min(.2,p.kick+w.recoil);shake+=w.recoil*35;flash=45;sfx('shot');for(let n=0;n<w.pellets;n++){const a=p.a+(Math.random()-.5)*w.spread*(ads?.42:1)*(1+p.kick*2),hitWall=ray(p.x,p.y,a,w.range);let best=null,bd=hitWall.d;for(const e of enemies){if(e.dead)continue;const d=Math.hypot(e.x-p.x,e.y-p.y),ad=Math.abs(C.angleDelta(Math.atan2(e.y-p.y,e.x-p.x),a));if(d<bd&&ad<(.23*e.size)/(d+.1)&&clearLine(p.x,p.y,e.x,e.y)){best=e;bd=d}}shots.push({a,d:Math.min(bd,hitWall.d),life:70,color:w.color});if(best){const head=Math.random()<(.18+(ads?.12:0));const dmg=C.damageAtRange(w.dmg,bd,w.fall,w.range,w.min)*(head?1.65:1);best.hp-=dmg;best.hit=110;particle(best.x,best.y,head?'#fff1b3':'#ff5e43',5,2.4,260);hitmark();sfx('hit');if(best.hp<=0)kill(best,head)}else if(hitWall.d<w.range)particle(hitWall.x,hitWall.y,'#ffc36b',3,1.1,180)}shells.push({x:W*.57,y:H*.68,vx:80+Math.random()*80,vy:-100-Math.random()*80,r:0,life:700});hud()}
function kill(e,head){if(e.dead)return;e.dead=true;p.kills++;p.waveKills++;p.combo=Math.min(4,p.combo+.25);p.comboAt=performance.now();const pts=Math.floor((e.elite?1000:e.type==='marksman'?220:e.type==='rusher'?160:120)*p.combo*(head?1.4:1));p.score+=pts;particle(e.x,e.y,e.elite?'#ff9b3f':'#e84b35',e.elite?35:16,e.elite?6:4,700);feed((head?'HEADSHOT · ':'')+(e.elite?'JUGGERNAUT':e.type.toUpperCase())+' +'+pts);sfx('kill');if(Math.random()<.16)pickups.push({x:e.x,y:e.y,type:Math.random()<.55?'ammo':'armor',life:15000});if(e.elite){$('boss').style.display='none';notice('高价值目标清除','获得战术补给奖励');p.armor=Math.min(100,p.armor+40)}if(p.waveKills>=C.waveTarget(p.wave)){nextWaveAt=performance.now()+3000;notice('区域暂时安全','下一波威胁正在接近')}}
function explode(b){if(b.dead)return;b.dead=true;shake=18;damageFlash=120;sfx('boom');particle(b.x,b.y,'#ff8d34',50,8,900);for(const e of enemies){const d=Math.hypot(e.x-b.x,e.y-b.y);if(d<4){e.hp-=110*(1-d/5);if(e.hp<=0)kill(e,false)}}if(Math.hypot(p.x-b.x,p.y-b.y)<3.5)hurt(28)}
function reload(){const w=weapons[weapon];if(reloading||w.mag===w.max||w.res<=0)return;reloading=true;reloadAt=performance.now()+w.reload;sfx('reload');$('mode').textContent='RELOADING...'}
function finishReload(){const w=weapons[weapon],need=w.max-w.mag,take=Math.min(need,w.res);w.mag+=take;w.res-=take;reloading=false;hud()}
function swap(){weapon=(weapon+1)%weapons.length;reloading=false;hud();notice(weapons[weapon].name,weapons[weapon].mode)}
function hurt(d){const r=C.absorbDamage(d,p.armor,.58);p.armor=r.armor;p.hp-=r.hpDamage;shake=12;damageFlash=260;p.combo=1;sfx('hurt');$('damageDir').style.opacity=1;setTimeout(()=>$('damageDir').style.opacity=0,180);if(p.hp<=0)die();hud()}
function die(){p.alive=false;state='dead';fireHeld=false;$('menu').style.display='flex';$('menu').querySelector('.kicker').textContent='OPERATOR DOWN';$('menu').querySelector('h1').innerHTML='任务<br>失败<span>得分 '+String(p.score).padStart(6,'0')+'</span>';$('menu').querySelector('.desc').textContent='灰港防线失守。调整装备，重新进入战区。';$('start').textContent='重新部署'}
function feed(t){const d=document.createElement('div');d.className='kill';d.textContent=t;$('killfeed').prepend(d);setTimeout(()=>d.remove(),3300)}
function notice(a,b){const n=$('notice');n.querySelector('.noticeMain').textContent=a;n.querySelector('.noticeSub').textContent=b;n.animate([{opacity:0,transform:'translate(-50%,-60%)'},{opacity:1,transform:'translate(-50%,-50%)'},{opacity:1},{opacity:0}],{duration:2600});}
function hitmark(){const h=$('hitmarker');h.classList.remove('on');void h.offsetWidth;h.classList.add('on')}
function hud(){const w=weapons[weapon];$('hp').style.width=C.clamp(p.hp,0,100)+'%';$('hpN').textContent=Math.ceil(Math.max(0,p.hp));$('armor').style.width=p.armor+'%';$('armorN').textContent=Math.ceil(p.armor);$('stamina').style.width=p.stamina+'%';$('mag').textContent=w.mag;$('reserve').textContent=w.res;$('weaponName').textContent=w.name;$('mode').textContent=reloading?'RELOADING...':w.mode;$('score').textContent=String(p.score).padStart(6,'0');$('wave').textContent=String(p.wave).padStart(2,'0');$('combo').textContent='x'+p.combo.toFixed(1);$('progress').textContent='威胁波次 '+String(p.wave).padStart(2,'0')+' · 目标 '+p.waveKills+'/'+C.waveTarget(p.wave)}
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='r')reload();if(e.key==='q')swap();if(e.key==='Shift')sprinting=true});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;if(e.key==='Shift')sprinting=false});canvas.addEventListener('mousedown',e=>{if(e.button===0)fireHeld=true;if(e.button===2)ads=true});addEventListener('mouseup',e=>{if(e.button===0)fireHeld=false;if(e.button===2)ads=false});addEventListener('mousemove',e=>{if(state==='play'&&document.pointerLockElement===canvas)p.a+=e.movementX*.0022});canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('click',()=>{if(state==='play')canvas.requestPointerLock?.()});
function bindHold(id,start,end){const el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);start()});el.addEventListener('pointerup',e=>{e.preventDefault();end?.()});el.addEventListener('pointercancel',()=>end?.())}bindHold('fire',()=>fireHeld=true,()=>fireHeld=false);bindHold('ads',()=>ads=true,()=>ads=false);bindHold('sprint',()=>sprinting=true,()=>sprinting=false);$('reload').onpointerdown=e=>{e.preventDefault();reload()};$('swap').onpointerdown=e=>{e.preventDefault();swap()};
let joy={id:null,x:0,y:0};$('stick').addEventListener('pointerdown',e=>{joy.id=e.pointerId;$('stick').setPointerCapture(e.pointerId)});$('stick').addEventListener('pointermove',e=>{if(e.pointerId!==joy.id)return;const r=$('stick').getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),d=Math.max(1,Math.hypot(dx,dy)),m=Math.min(36,d);joy.x=dx/d*m/36;joy.y=dy/d*m/36;$('knob').style.transform=`translate(${joy.x*34}px,${joy.y*34}px)`});function joyEnd(){joy.id=null;joy.x=joy.y=0;$('knob').style.transform='none'}$('stick').addEventListener('pointerup',joyEnd);$('stick').addEventListener('pointercancel',joyEnd);
let aimId=null,aimX=0;canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'&&e.clientX>W*.42){aimId=e.pointerId;aimX=e.clientX;canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(e.pointerId===aimId){p.a+=(e.clientX-aimX)*.004;aimX=e.clientX}});canvas.addEventListener('pointerup',e=>{if(e.pointerId===aimId)aimId=null});
function update(dt,t){if(state!=='play')return;const sec=dt/1000;if(reloading&&t>=reloadAt)finishReload();if(t-p.comboAt>4200)p.combo=Math.max(1,p.combo-dt*.0007);let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)-joy.y,side=(keys.d?1:0)-(keys.a?1:0)+joy.x;const run=sprinting&&p.stamina>2&&(Math.abs(f)+Math.abs(side)>.1),speed=run?4.8:2.8;p.stamina=C.clamp(p.stamina+(run?-25:14)*sec,0,100);const dx=(Math.cos(p.a)*f+Math.cos(p.a+Math.PI/2)*side)*speed*sec,dy=(Math.sin(p.a)*f+Math.sin(p.a+Math.PI/2)*side)*speed*sec,nx=p.x+dx,ny=p.y+dy;if(!solid(nx,p.y))p.x=nx;if(!solid(p.x,ny))p.y=ny;p.bob+=Math.hypot(dx,dy)*8;p.kick*=Math.pow(.04,sec);shake*=Math.pow(.03,sec);flash=Math.max(0,flash-dt);damageFlash=Math.max(0,damageFlash-dt);if(fireHeld)shoot();
for(const e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy),los=clearLine(e.x,e.y,p.x,p.y);if(d>.85){const sp=e.speed*(los?1:.65),nx=e.x+dx/d*sp*sec,ny=e.y+dy/d*sp*sec;if(!solid(nx,e.y))e.x=nx;if(!solid(e.x,ny))e.y=ny}e.cool-=dt;if(los&&e.cool<=0&&d<(e.type==='rusher'?1.4:e.type==='marksman'?18:10)){e.cool=(e.type==='juggernaut'?650:e.type==='rusher'?750:1100)+Math.random()*500;if(e.type==='rusher'||d<1.5)hurt(e.damage);else{shots.push({a:Math.atan2(p.y-e.y,p.x-e.x),d,life:90,enemy:true,color:'#ff493e',ox:e.x,oy:e.y});if(Math.random()<C.clamp(.75-d*.035,.18,.68))hurt(e.damage)}}}
enemies=enemies.filter(e=>!e.dead);for(const b of barrels){if(b.dead)continue;for(const s of shots){if(!s.checked&&C.segmentCircle(p.x,p.y,p.x+Math.cos(s.a)*s.d,p.y+Math.sin(s.a)*s.d,b.x,b.y,.32)){b.hp-=weapons[weapon].dmg;s.checked=true;if(b.hp<=0)explode(b)}}}for(const q of pickups){q.life-=dt;if(Math.hypot(q.x-p.x,q.y-p.y)<.8){if(q.type==='armor')p.armor=Math.min(100,p.armor+35);else weapons.forEach(w=>w.res+=w.max*2);q.life=0;notice('战术补给',q.type==='armor'?'护甲恢复 +35':'全武器弹药补充')}}pickups=pickups.filter(q=>q.life>0);
particles.forEach(q=>{q.x+=q.vx*sec;q.y+=q.vy*sec;q.vx*=.96;q.vy*=.96;q.life-=dt});particles=particles.filter(q=>q.life>0);shots.forEach(s=>s.life-=dt);shots=shots.filter(s=>s.life>0);shells.forEach(s=>{s.x+=s.vx*sec;s.y+=s.vy*sec;s.vy+=420*sec;s.r+=8*sec;s.life-=dt});shells=shells.filter(s=>s.life>0);
if(nextWaveAt&&t>=nextWaveAt){p.wave++;p.waveKills=0;nextWaveAt=0;p.armor=Math.min(100,p.armor+20);for(let i=0;i<Math.min(5+p.wave,10);i++)spawnEnemy(p.wave%4===0&&i===0);notice('威胁波次 '+String(p.wave).padStart(2,'0'),p.wave%4===0?'侦测到重装执行者':'敌军增援已抵达')}else if(!nextWaveAt){spawnClock-=dt;if(spawnClock<=0&&enemies.length<Math.min(5+p.wave,12)){spawnEnemy();spawnClock=1000+Math.random()*1800}}hud()}
function project(x,y){const dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy),a=C.angleDelta(Math.atan2(dy,dx),p.a);return{d,a,x:W/2+a/(ads?.72:1.05)*W,y:H/2,size:H/(d+.1)}}
function render(t){const fov=ads?.72:1.05,rays=Math.max(160,Math.floor(W/(W<700?4:3)));ctx.save();if(shake>1)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);const sky=ctx.createLinearGradient(0,0,0,H*.56);sky.addColorStop(0,'#111f28');sky.addColorStop(.55,'#38505a');sky.addColorStop(1,'#927557');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H*.55);ctx.fillStyle='#172023';ctx.fillRect(0,H*.55,W,H*.45);ctx.fillStyle='rgba(220,176,112,.18)';ctx.beginPath();ctx.arc(W*.78,H*.18,42,0,7);ctx.fill();
const z=[];for(let i=0;i<rays;i++){const a=p.a-fov/2+fov*i/rays,h=ray(p.x,p.y,a),d=h.d*Math.cos(a-p.a),wh=Math.min(H*1.8,H/(d+.05)*1.1),x=i*W/rays,w=W/rays+1,shade=C.clamp(1-d/35,.16,1),base=h.t===2?[105,112,108]:h.t===3?[83,102,110]:[93,82,70];ctx.fillStyle=`rgb(${base[0]*shade},${base[1]*shade},${base[2]*shade})`;ctx.fillRect(x,H*.52-wh/2,w,wh);const fog=C.clamp((d-12)/24,0,.7);ctx.fillStyle=`rgba(111,126,126,${fog})`;ctx.fillRect(x,H*.52-wh/2,w,wh);z[i]=d}
const objs=[];enemies.forEach(e=>{if(!e.dead)objs.push({kind:'enemy',o:e,...project(e.x,e.y)})});barrels.forEach(b=>{if(!b.dead)objs.push({kind:'barrel',o:b,...project(b.x,b.y)})});pickups.forEach(q=>objs.push({kind:'pickup',o:q,...project(q.x,q.y)}));particles.forEach(q=>objs.push({kind:'particle',o:q,...project(q.x,q.y)}));objs.filter(v=>Math.abs(v.a)<fov*.58&&v.d>.18&&v.d<40).sort((a,b)=>b.d-a.d).forEach(v=>{const zi=C.clamp(Math.floor((v.a/fov+.5)*rays),0,rays-1);if(z[zi]<v.d-.25)return;const s=v.size;if(v.kind==='enemy'){const e=v.o,hh=s*e.size,ww=hh*.48,x=v.x-ww/2,y=H*.52-hh*.52;ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(v.x,y+hh,ww*.65,hh*.1,0,0,7);ctx.fill();ctx.fillStyle=e.hit?'#f5c09f':e.color;ctx.fillRect(x,y+hh*.28,ww,hh*.57);ctx.fillStyle=e.elite?'#242b2d':'#303a3b';ctx.fillRect(x-ww*.16,y+hh*.34,ww*.18,hh*.42);ctx.fillRect(x+ww*.98,y+hh*.34,ww*.18,hh*.42);ctx.fillStyle='#b68b70';ctx.beginPath();ctx.arc(v.x,y+hh*.19,ww*.28,0,7);ctx.fill();ctx.fillStyle='#182329';ctx.fillRect(v.x-ww*.3,y+hh*.11,ww*.6,hh*.09);ctx.fillStyle='#111';ctx.fillRect(x+ww*.18,y+hh*.82,ww*.24,hh*.18);ctx.fillRect(x+ww*.62,y+hh*.82,ww*.24,hh*.18);if(e.hit||e.elite){ctx.fillStyle='#25100e';ctx.fillRect(x,y-6,ww,3);ctx.fillStyle=e.elite?'#ff5b49':'#ffb247';ctx.fillRect(x,y-6,ww*C.clamp(e.hp/e.max,0,1),3)}if(e.elite)$('bossFill').style.width=C.clamp(e.hp/e.max*100,0,100)+'%'}else if(v.kind==='barrel'){ctx.fillStyle='#9c382c';ctx.fillRect(v.x-s*.18,H*.52-s*.28,s*.36,s*.56);ctx.fillStyle='#f0b441';ctx.fillRect(v.x-s*.18,H*.52-s*.08,s*.36,s*.1)}else if(v.kind==='pickup'){const pulse=1+Math.sin(t*.008)*.12;ctx.fillStyle=v.o.type==='armor'?'#59cce4':'#ffc458';ctx.globalAlpha=.8;ctx.fillRect(v.x-s*.14*pulse,H*.52-s*.22,s*.28*pulse,s*.28);ctx.globalAlpha=1}else{ctx.globalAlpha=C.clamp(v.o.life/v.o.max,0,1);ctx.fillStyle=v.o.color;ctx.fillRect(v.x,H*.52-s*.08,v.o.size,v.o.size);ctx.globalAlpha=1}});
for(const s of shots){ctx.globalAlpha=C.clamp(s.life/70,0,1);ctx.strokeStyle=s.color;ctx.lineWidth=s.enemy?2:1;ctx.beginPath();if(s.enemy){const a=C.angleDelta(s.a,p.a);ctx.moveTo(W/2+a/fov*W,H*.48);ctx.lineTo(W/2,H*.52)}else{ctx.moveTo(W*.54,H*.68);ctx.lineTo(W/2+C.angleDelta(s.a,p.a)/fov*W,H*.5)}ctx.stroke()}ctx.globalAlpha=1;drawWeapon(t);shells.forEach(s=>{ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.r);ctx.fillStyle='#d4a84d';ctx.fillRect(-2,-5,4,10);ctx.restore()});if(flash>0){ctx.fillStyle=`rgba(255,192,73,${flash/100})`;ctx.beginPath();ctx.arc(W*.52,H*.61,14+Math.random()*15,0,7);ctx.fill()}if(damageFlash){ctx.fillStyle=`rgba(185,15,8,${damageFlash/900})`;ctx.fillRect(0,0,W,H)}ctx.restore();drawWeather(t);drawRadar();$('crosshair').style.transform=`translate(-50%,-50%) scale(${1+p.kick*5})`}
function drawWeapon(t){const w=weapons[weapon],bob=Math.sin(p.bob)*5*(ads?.25:1),x=W*(ads?.5:.62)+bob,y=H*(ads?.73:.78)+Math.abs(Math.cos(p.bob))*3+p.kick*H*.7;ctx.save();ctx.translate(x,y);ctx.rotate(-.18-p.kick*.9);const sc=Math.min(W/900,H/480);ctx.scale(sc,sc);ctx.fillStyle=weapon===1?'#4f3b2c':'#252c2e';ctx.fillRect(-80,-16,170,42);ctx.fillStyle='#111719';ctx.fillRect(-110,-9,70,14);ctx.fillStyle='#455053';ctx.fillRect(-45,-22,95,12);ctx.fillStyle='#15191a';ctx.fillRect(10,20,24,65);ctx.fillStyle='#303638';ctx.fillRect(50,22,17,48);ctx.fillStyle='#8ba2a4';for(let i=0;i<4;i++)ctx.fillRect(-34+i*20,-18,10,3);if(weapon===3){ctx.fillStyle='#172226';ctx.fillRect(-30,-42,74,18);ctx.fillStyle='#70b9c8';ctx.beginPath();ctx.arc(-22,-33,7,0,7);ctx.fill()}ctx.restore()}
function drawWeather(t){if(weather.length<80)for(let i=weather.length;i<80;i++)weather.push({x:Math.random()*W,y:Math.random()*H,s:12+Math.random()*25});ctx.strokeStyle='rgba(185,216,220,.16)';ctx.lineWidth=1;ctx.beginPath();for(const q of weather){q.x-=q.s*.012;q.y+=q.s*.025;if(q.y>H){q.y=-20;q.x=Math.random()*W}ctx.moveTo(q.x,q.y);ctx.lineTo(q.x-5,q.y+q.s)}ctx.stroke()}
function drawRadar(){rctx.clearRect(0,0,104,104);rctx.strokeStyle='rgba(100,190,205,.25)';rctx.beginPath();rctx.arc(52,52,25,0,7);rctx.arc(52,52,49,0,7);rctx.stroke();rctx.fillStyle='#d9ffff';rctx.beginPath();rctx.moveTo(52,46);rctx.lineTo(48,57);rctx.lineTo(56,57);rctx.fill();for(const e of enemies){const dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy);if(d>14)continue;const a=Math.atan2(dy,dx)-p.a+Math.PI/2;rctx.fillStyle=e.elite?'#ffb13c':'#ff554a';rctx.beginPath();rctx.arc(52+Math.cos(a)*d*3.2,52+Math.sin(a)*d*3.2,e.elite?3:1.8,0,7);rctx.fill()}}
function loop(t){const dt=Math.min(50,t-last||16);last=t;update(dt,t);render(t);requestAnimationFrame(loop)}
$('start').onclick=()=>{initAudio();reset();state='play';$('menu').style.display='none';document.documentElement.requestFullscreen?.().catch(()=>{});screen.orientation?.lock?.('landscape').catch(()=>{});setTimeout(()=>canvas.requestPointerLock?.(),80)};reset();state='menu';requestAnimationFrame(loop);
})();